name: CI

# --------------- When to run this workflow ---------------
on:
  push:
    branches: [ main ]          # on every git push to 'main'
  pull_request:
    branches: [ main ]          # on every PR targeting 'main'

# --------------- Define one or more jobs ---------------
jobs:
  test:                          # a single job called "test"
    runs-on: ubuntu-latest       # which VM image to use

    steps:
      # 1) Check out your repository code
      - uses: actions/checkout@v3

      # 2) Set up Python on the runner
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3) Install your project’s dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask fastf1 pytest

      # 4) Run your test suite
      - name: Run pytest
        run: pytest -q
